version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5062:5062"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:5062
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock # for running docker inside backend
    working_dir: /app
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5062"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

networks:
  default:
    driver: bridge
